version: 1.0
component: deployment
shell: bash
env:
  variables:
    # Local variables
  vaultVariables:
    # Vault variables
files:
  # This section is to define how the files in the artifact shall
  # be put on the compute instance
  - source: /
    destination: /tmp/
steps:
  # This section is to define the scripts that each step shall run on the instance after file copy.
  - stepType: Command
    name: Install OCI CLI
    command: |
      cd ~
      python3 -m pip install --user oci-cli

    timeoutInSeconds: 5000
    shell: bash
    onFailure:
      - stepType: Command
        name: "Failure Handling"
        timeoutInSeconds: 1200
        command: |
          echo "Handled failure"
 
  - stepType: Command
    name: "Install local JDK17"
    timeoutInSeconds: 10000
    command: |
      cd ~
      mkdir InstalledSoftware
      cd InstalledSoftware
      wget -q https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz
      tar xf *tar.gz
      rm *tar.gz
      ls -l
      export JAVA_HOME=`echo -n ~/InstalledSoftware/jdk-*`
      export PATH=$JAVA_HOME/bin:$PATH
      echo Path is
      echo $PATH
      echo JAVA_HOME is
      echo $JAVA_HOME
      java -version
    onFailure:
      - stepType: Command
        timeoutInSeconds: 40
        command: |
          echo "Handling Failure"
          echo "Failure successfully handled"
        timeoutInSeconds: 400
  
  
  - stepType: Command
    name: Run the Application
    command: |
      cd ~
      pid_count=`ps -fe |grep openshift-test-0.0.1-SNAPSHOT.jar | grep -v grep | wc -l`
      pid=`ps -fe |grep openshift-test-0.0.1-SNAPSHOT.jar | grep -v grep |awk '{print $2}'`
      if [[ $pid_count == 1 ]]  ;then kill -9 $pid ; fi
      export OCI_CLI_AUTH=instance_principal
      export PATH=$PATH:~/.local/bin/
      oci artifacts generic artifact download-by-path --repository-id ${ARTIFACT_REPO_OCID} --artifact-path ${ARTIFACT_NAME} --artifact-version ${APPLICATION_VERSION} --file openshift-test-0.0.1-SNAPSHOT.jar
      sudo ls -ltr
      echo version java `java --version`
      echo quien soy `whoami`
      sudo firewall-cmd --permanent --zone=public --add-service=http
      sudo firewall-cmd --permanent --zone=public --add-port=8090/tcp
      sudo systemctl restart firewalld
      sudo java -jar openshift-test-0.0.1-SNAPSHOT.jar

    timeoutInSeconds: 5000
    shell: bash
    onFailure:
      - stepType: Command
        name: "Failure Handling"
        timeoutInSeconds: 1200
        command: |
          echo "Handled failure"